=== prabhatsingh2408/jlc/advance java/xml/Lab1/jlc.dtd
<!ELEMENT jlc (student*,course+)>
<!ELEMENT student (sname,email+)>
<!ELEMENT course (cname,cost,faculty)>
<!ELEMENT sname (#PCDATA)>
<!ELEMENT email (oemail,pemail)>
<!ELEMENT oemail (#PCDATA)>
<!ELEMENT pemail (#PCDATA)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT faculty (#PCDATA)>

<!ATTLIST student
sid CDATA #REQUIRED
job CDATA #IMPLIED>

<!ATTLIST course
cid CDATA #REQUIRED
free (yes|no) "no">

<!ENTITY f1 "PARBHAT KUMAR SINGH">
<!ENTITY COMPANY "JAVA LEARNING CENTER">

=== prabhatsingh2408/jlc/advance java/xml/Lab1/jlc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jlc PUBLIC "-//Java Learning Center//DTD 
                        JLCapp 1.0//EN" "jlc.dtd">
<jlc>
<student sid="11" job="yes">
<sname>prabhat</sname>
<email>
<oemail>prabhat@gmail</oemail>
<pmail>prabhat@gmail</pmail>
</email>
</student>
<student sid="12" job="no">
<sname>rama</sname>
<email>
<oemail>rama@gmail</oemail>
<pmail>rama@gmail</pmail>
</email>
</student>
<course cid="101" free="yes">
<cname>XML</cname>
<cost>500</cost>
<faculty>&f1</faculty>
</course>
<course cid="102" >
<cname>Web Services</cname>
<cost>4500</cost>
<faculty>&f1</faculty>
</course>
</jlc>
