=== prabhatsingh2408/jlc/advance java/xml/Lab3/jlc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<sd:schema 
        xmlns:sd="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.jlcindia.com/jlc" 
        xmlns:jlc="http://www.jlcindia.com/jlc" 
        elementFormDefault="qualified">
        
        <sd:element name="student">
        <sd:complexType>
        <sd:sequence>
        <sd:element name="sname" type="sd:string" minOccurs="1" maxOccurs="1"/>
        <sd:element name="email" type="sd:string" minOccurs="1" maxOccurs="unbounded"/>
        <sd:element name="phone" type="sd:long" minOccurs="1" maxOccurs="1"/>
        <sd:element name="fee" type="sd:double" minOccurs="0" maxOccurs="1"/>
        </sd:sequence>
        <sd:attribute name="sid" type="sd:string" use="required"/>
        </sd:complexType>
        </sd:element>
        
        <sd:element name="course">
        <sd:complexType>
        <sd:sequence>
        <sd:element name="cname" type="sd:string" minOccurs="1" maxOccurs="1"/>
        <sd:element name="cost" type="sd:double" minOccurs="1" maxOccurs="unbounded"/>
        </sd:sequence>
        <sd:attribute name="cid" type="sd:string" use="optional"/>
        </sd:complexType>
        </sd:element>
        
        <sd:element name="jlc">
        <sd:complexType>
        <sd:sequence>
        <sd:element ref="jlc:student"/>
        <sd:element ref="jlc:course"/>
        </sd:sequence>
        </sd:complexType>
        </sd:element>
</sd:schema>

=== prabhatsingh2408/jlc/advance java/xml/Lab3/jlc.xml
<?xml version="1.0" encoding="UTF-8"?>
<jlc xmlns="http://www.jlcindia.com/jlc"
 xmlns:xsi="http//www.w3.org/2001/XMLSchema-instance"
 schemaLocation="http://www.jlcindia.com/jlc jlc.xsd">
 
 <student sid="11">
 <sname>sri</sname>
 <email>sri@gmail</email>
 <phone>12345</phone>
 <fee>999.99</fee>
 </student>
 <course cid="c-99">
 <cname>JAVA</cname>
 <cost>2000</cost>
 </course>
 </jlc>
